name: your-portfolio

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: your-portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
